#!/usr/bin/env python3
"""
gravitron init — Scaffold a new project for Gravitron awareness.

Creates:
  ./.gravitron           (project manifest file)
  ./.antigravityrules    (symlink to global rules if they exist)

Then runs an initial ingest snapshot to register the project.
"""
import os
import sys
import subprocess
import datetime

GRAVITRON_ROOT  = os.environ.get("GRAVITRON_ROOT", os.path.expanduser("~/.gravitron"))
GRAVITRON_STATE = os.environ.get("GRAVITRON_STATE", os.path.expanduser("~/.gemini/antigravity"))

MANIFEST_TEMPLATE = """\
# Gravitron Project Manifest
# Auto-generated by: gravitron init

project: {name}
created: {date}
state_silo: {state}

# Skills loaded for this project (in addition to global skills)
skills: []

# Snapshot preferences
snap:
  default_mode: blueprint
  ignore_extra: []
"""

RULES_TEMPLATE = """\
# Project Rules — {name}
# These rules govern agentic behavior within this project.
# Loaded automatically by the Gravitron harness.

## Core Constraints
1. All changes must be reversible (maintain a blueprint snapshot).
2. Verify tool outputs — no hallucinated file paths or command results.
3. Follow the Karpathy guidelines for code simplicity and blast-radius containment.

## Project-Specific Notes
# Add project-specific behavioral guardrails below.
"""

def init_project(target_dir=None):
    project_dir = os.path.abspath(target_dir or os.getcwd())
    project_name = os.path.basename(project_dir)

    gravitron_dir = os.path.join(project_dir, ".gravitron")
    manifest_path = os.path.join(project_dir, ".gravitron")  # file, not dir
    rules_path    = os.path.join(project_dir, ".antigravityrules")

    # Check if already initialized
    if os.path.exists(manifest_path):
        print(f"  ⚠  Already initialized: {manifest_path}")
        print(f"     Project '{project_name}' is registered with Gravitron.")
        return

    print(f"=== [gravitron init] Initializing Project: {project_name} ===")
    print(f"  Path: {project_dir}")
    print()

    # 1. Write .gravitron manifest file
    manifest_content = MANIFEST_TEMPLATE.format(
        name=project_name,
        date=datetime.datetime.now().strftime("%Y-%m-%d"),
        state=GRAVITRON_STATE
    )
    with open(manifest_path, "w") as f:
        f.write(manifest_content)
    print(f"  ✓ Created: .gravitron (project manifest)")

    # 2. Write .antigravityrules
    if not os.path.exists(rules_path):
        with open(rules_path, "w") as f:
            f.write(RULES_TEMPLATE.format(name=project_name))
        print(f"  ✓ Created: .antigravityrules (project governance)")
    else:
        print(f"  ✓ Rules already exist: .antigravityrules")

    # 3. Run initial blueprint snapshot
    print(f"\n  🔄 Running initial blueprint snapshot...")
    try:
        res = subprocess.run(
            ["gravitron", "snap", ".", "--project", project_name],
            cwd=project_dir, capture_output=True, text=True
        )
        if res.returncode == 0:
            print(f"  ✓ {res.stdout.strip()}")
        else:
            print(f"  ⚠  Snapshot incomplete: {res.stderr.strip()}")
    except Exception as e:
        print(f"  ⚠  Snapshot skipped: {e}")

    print()
    print(f"  🪐 Project '{project_name}' is now Gravitron-aware.")
    print(f"     → gravitron brief        — Session context")
    print(f"     → gravitron snap .       — Update snapshot")
    print(f"     → gravitron doctor       — Health check")

if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else None
    init_project(target)
